AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  magneto-app

  Sample SAM Template for magneto-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MutantFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mutant/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Mutant:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mutant
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MutantApi:
    Description: "API Gateway endpoint URL for Prod stage for Mutant function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mutant/"
  MutantFunction:
    Description: "Mutant Lambda Function ARN"
    Value: !GetAtt MutantFunction.Arn
  MutantFunctionIamRole:
    Description: "Implicit IAM Role created for Mutant function"
    Value: !GetAtt MutantFunctionRole.Arn
